[package]
name = "hashcaster"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.16.1", features = ["extern_crate_alloc", "derive", "zeroable_maybe_uninit"]}
cfg-if = "1.0.0"
itertools = "0.13.0"
num-traits = "0.2.19"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1", features = ["derive"] }
unroll = "0.1.5"

[features]
parallel = []
default = ["parallel"]
